[package]
name = "pyohwa-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
pyohwa-core = { path = "../pyohwa-core" }
pyohwa-server = { path = "../pyohwa-server" }
clap = { version = "4", features = ["derive"] }
tokio = { workspace = true }
